/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture_sale_ordering_management_system;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yuw18
 */
public class Modify_Sales_Order_Quotation extends javax.swing.JFrame {
    public static String userID;
    public static String orderID;
    public static String Amount;
    public static String ItemID;
    public static String Product;
    public static String Category;
    public static String Price;
    public static String Salesperson;
    public static String Confirmation;
    public static String Officer;
    public static String Invoice;
    public static String Status;
    public static Date date;

    /**
     * Creates new form Modify_Sales_Order_Quotation
     * @param orderID
     * @param Amount
     * @param ItemID
     * @param Product
     * @param date
     * @param Category
     * @param Salesperson
     * @param Price
     * @param Confirmation
     * @param Officer
     * @param Invoice
     * @param Status
     */
    public void setInitialValues(String orderID, String Amount, String Product,String ItemID, String Category, String Price,String Salesperson, String Confirmation, String Officer, String Invoice, String Status, Date date) {
    jTextField_id.setText(orderID);
    jTextField_amount.setText(Amount);
    jComboBox_product.setSelectedItem(Product);
    jTextField_itemid.setText(ItemID);
    jTextField_category.setText(Category);
    jTextField_price.setText(Price);
    jTextField_salesperson.setText(Salesperson);
    jTextField_confirmation.setText(Confirmation);
    jTextField_officer.setText(Officer);
    jTextField_invoice.setText(Invoice);
    jTextField_status.setText(Status);
    jDateChooser.setDate(date); // Set the date in the date chooser
}
    
    public Modify_Sales_Order_Quotation(String userID, String orderID, String Amount,String ItemID, String Product, String Category, String Price,String Salesperson, String Confirmation, String Officer, String Invoice, String Status, Date date) {
        initComponents();
        
        jTextField_id.setEditable(false);
        jTextField_itemid.setEditable(false);
        jComboBox_product.setEditable(false);
        
        
        this.userID = userID;
        this.orderID = orderID;
        this.Amount = Amount;
        this.Product = Product;
        this.Category = Category;
        this.Price = Price;
        this.ItemID = ItemID;
        this.Salesperson = Salesperson;
        this.Confirmation = Confirmation;
        this.Officer = Officer;
        this.Invoice = Invoice;
        this.Status = Status;
        this.date = date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_amount = new javax.swing.JTextField();
        jTextField_salesperson = new javax.swing.JTextField();
        jTextField_confirmation = new javax.swing.JTextField();
        jTextField_officer = new javax.swing.JTextField();
        jTextField_invoice = new javax.swing.JTextField();
        jTextField_status = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jButton_modify = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_itemid = new javax.swing.JTextField();
        jTextField_category = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jComboBox_product = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MODIFY SALES ORDER QUOTATION");

        jLabel2.setText("ID：");

        jLabel3.setText("Amount :");

        jLabel4.setText("Date :");

        jLabel5.setText("Sales Person :");

        jLabel6.setText("Confirmation :");

        jLabel7.setText("Officer :");

        jLabel8.setText("Invoice :");

        jLabel9.setText("Status :");

        jButton_modify.setText("Modify");
        jButton_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifyActionPerformed(evt);
            }
        });

        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jLabel10.setText("Product :");

        jLabel11.setText("Item ID :");

        jLabel12.setText("Category :");

        jLabel13.setText("Price :");

        jComboBox_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_modify))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_id)
                                    .addComponent(jTextField_amount)
                                    .addComponent(jTextField_salesperson)
                                    .addComponent(jTextField_confirmation)
                                    .addComponent(jTextField_officer)
                                    .addComponent(jTextField_invoice)
                                    .addComponent(jTextField_status))))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_category, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_itemid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_itemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextField_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_salesperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_officer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_modify)
                    .addComponent(jButton_back))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private boolean modifySalesQuotation(String orderID, String Amount,String ItemID, String Product, String Category, String Price,String Salesperson, String Confirmation, String Officer, String Invoice, String Status, Date date) {
    try {
        Path inputFile = Path.of("Data/Sales_Quotation.txt");

        List<String> lines = Files.readAllLines(inputFile, StandardCharsets.UTF_8);

        boolean found = false;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
        String formattedDate = dateFormat.format(date); // Format the date

        for (int i = 0; i < lines.size() - 8; i += 9) {
            String line = lines.get(i);
            if (line.equals("ID: " + orderID)) {
                // Modify the existing booking
                lines.set(i, "ID: " + orderID);
                lines.set(i + 1, "Amount: " + Amount);
                lines.set(i + 1, "Item ID: " + ItemID);
                lines.set(i + 1, "Product: " + Product);
                lines.set(i + 1, "Category: " + Category);
                lines.set(i + 1, "Price: " + Price);
                lines.set(i + 2, "Date: " + formattedDate + ","); // Use the formatted date
                lines.set(i + 3, "Salesperson: " + Salesperson);
                lines.set(i + 4, "Confirmation: " + Confirmation);
                lines.set(i + 5, "Officer: " + Officer);
                lines.set(i + 6, "Invoice: " + Invoice);
                lines.set(i + 7, "Status: " + Status);
                found = true;
                break;
            }
        }

        if (!found) {
            System.out.println("Profile not found.");
            return false;
        }

        Files.write(inputFile, lines, StandardCharsets.UTF_8, StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING);

        return true;
    } catch (IOException e) {
        e.printStackTrace();
        return false;
    }
}
    private void jButton_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifyActionPerformed
    String orderID = jTextField_id.getText();
    String Amount = jTextField_amount.getText();
    String ItemID = jTextField_itemid.getText();
    String Product = jComboBox_product.getSelectedItem().toString();
    String Category = jTextField_category.getText();
    String Price = jTextField_price.getText();
    Date date = jDateChooser.getDate();
    String Salesperson = jTextField_salesperson.getText();
    String Confirmation = jTextField_confirmation.getText();
    String Officer = jTextField_officer.getText();
    String Invoice = jTextField_invoice.getText();
    String Status = jTextField_status.getText();

    // Validate input fields
    if (orderID.isEmpty() || Amount.isEmpty() || Status.isEmpty() || Salesperson.isEmpty() || Confirmation.isEmpty() || Officer.isEmpty() || Invoice.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all the required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Perform the booking
    boolean isModified = modifySalesQuotation(orderID, Amount,ItemID, Product, Category, Price, Salesperson, Confirmation, Officer, Invoice, Status, date);

    if (isModified) {
        JOptionPane.showMessageDialog(this, "Sales Order Quotation modified successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to modify the Sales Order Quotation. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton_modifyActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        Manage_Sales_Order_Quotation manage_sales_order_quotation = new Manage_Sales_Order_Quotation(userID);
        manage_sales_order_quotation.displaySales();
        manage_sales_order_quotation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jComboBox_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify_Sales_Order_Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify_Sales_Order_Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify_Sales_Order_Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_Sales_Order_Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            Modify_Sales_Order_Quotation modifySalesOrderQuotation = new Modify_Sales_Order_Quotation(userID,orderID, Amount,ItemID, Product, Category, Price, Salesperson, Confirmation, Officer, Invoice, Status, date);
            modifySalesOrderQuotation.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_modify;
    private javax.swing.JComboBox<String> jComboBox_product;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_amount;
    private javax.swing.JTextField jTextField_category;
    private javax.swing.JTextField jTextField_confirmation;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_invoice;
    private javax.swing.JTextField jTextField_itemid;
    private javax.swing.JTextField jTextField_officer;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_salesperson;
    private javax.swing.JTextField jTextField_status;
    // End of variables declaration//GEN-END:variables
}
